name: huanlxh
on:
  workflow_dispatch:
  schedule:
    - cron: '54 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huanlxh
        env:
          lyyu853: ${{ secrets.lyyu853 }}
        run: |
          echo $lyyu853 | jq -r .ho666 | /bin/bash
          echo $w351 | jq -r .ycsq18137 | /bin/bash
          echo $sigts446 | jq -r .tiay9656 | /bin/bash
          echo $tghi67785 | jq -r .j833 | /bin/bash

